import { Food } from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Ndolé et plantains',
    cookTime: '1-2 heures',
    price: 15,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.8,
    imageUrl: 'assets/food-ndole.jpg',
    tags: ['Traditionnel', 'Ndolé', 'Dîner'],
  },
  {
    id: '2',
    name: 'Poulet DG',
    price: 18,
    cookTime: '1-1.5 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.9,
    imageUrl: 'assets/food-pouletdg.jpg',
    tags: ['Festif', 'Poulet', 'Dîner'],
  },
  {
    id: '3',
    name: 'Eru',
    price: 12,
    cookTime: '2-3 heures',
    favorite: false,
    origins: ['Cameroun', 'Nigeria'],
    stars: 4.7,
    imageUrl: 'assets/food-eru.jpg',
    tags: ['Traditionnel', 'Eru', 'Dîner'],
  },
  {
    id: '4',
    name: 'Koki',
    price: 10,
    cookTime: '1-2 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.6,
    imageUrl: 'assets/food-koki.jpg',
    tags: ['Végétarien', 'Koki', 'Dîner'],
  },
  {
    id: '5',
    name: 'Brochettes de Soya',
    price: 8,
    cookTime: '20-30 minutes',
    favorite: false,
    origins: ['Cameroun'],
    stars: 4.5,
    imageUrl: 'assets/food-soya.jpg',
    tags: ['StreetFood', 'Soya', 'Snack'],
  },
  {
    id: '6',
    name: 'Poisson Braisé',
    price: 20,
    cookTime: '30-45 minutes',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.9,
    imageUrl: 'assets/food-poissonbraise.jpg',
    tags: ['Traditionnel', 'Poisson', 'Dîner'],
  },
  {
    id: '7',
    name: 'Taro et sauce jaune',
    price: 16,
    cookTime: '2 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.8,
    imageUrl: 'assets/food-taro.jpg',
    tags: ['Traditionnel', 'Taro', 'Dîner'],
  },
  {
    id: '8',
    name: 'Beignets Haricots',
    price: 5,
    cookTime: '30-45 minutes',
    favorite: false,
    origins: ['Cameroun'],
    stars: 4.4,
    imageUrl: 'assets/food-beignetsharicots.jpg',
    tags: ['StreetFood', 'Beignets', 'Snack'],
  },
]
