import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';
export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Ndolé et plantains',
    cookTime: '1-2 heures',
    price: 15,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.8,
    imageUrl: 'assets/food-ndole.jpg',
    tags: ['Traditionnel', 'Dîner'],
  },
  {
    id: '2',
    name: 'Poulet DG',
    price: 18,
    cookTime: '1-1.5 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.9,
    imageUrl: 'assets/food-pouletdg.jpg',
    tags: ['Festif', 'Poulet', 'Dîner'],
  },
  {
    id: '3',
    name: 'Eru',
    price: 12,
    cookTime: '2-3 heures',
    favorite: false,
    origins: ['Cameroun', 'Nigeria'],
    stars: 4.7,
    imageUrl: 'assets/food-eru.jpg',
    tags: ['Traditionnel', 'Eru', 'Dîner'],
  },
  {
    id: '4',
    name: 'Koki',
    price: 10,
    cookTime: '1-2 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.6,
    imageUrl: 'assets/food-koki.jpg',
    tags: ['Végétarien', 'Koki', 'Dîner'],
  },
  {
    id: '5',
    name: 'Brochettes de Soya',
    price: 8,
    cookTime: '20-30 minutes',
    favorite: false,
    origins: ['Cameroun'],
    stars: 4.5,
    imageUrl: 'assets/food-soya.jpg',
    tags: ['StreetFood', 'Soya', 'Snack'],
  },
  {
    id: '6',
    name: 'Poisson Braisé',
    price: 20,
    cookTime: '30-45 minutes',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.9,
    imageUrl: 'assets/food-poissonbraise.jpg',
    tags: ['Traditionnel', 'Poisson', 'Dîner'],
  },
  {
    id: '7',
    name: 'Taro et sauce jaune',
    price: 16,
    cookTime: '2 heures',
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.8,
    imageUrl: 'assets/food-taro.jpg',
    tags: ['Traditionnel', 'Dîner'],
  },
  {
    id: '8',
    name: 'Beignets Haricots',
    price: 5,
    cookTime: '30-45 minutes',
    favorite: false,
    origins: ['Cameroun'],
    stars: 4.4,
    imageUrl: 'assets/food-beignetsharicots.jpg',
    tags: ['StreetFood', 'Beignets', 'Snack'],
  },
  {
    id: '9',
    name: 'Okok',
    cookTime: '2-3 heures',
    price: 14,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.8,
    imageUrl: 'assets/food-okok.jpg',
    tags: ['Traditionnel', 'Dîner', 'Végétarien'],
  },
  {
    id: '10',
    name: 'Sangah',
    cookTime: '2 heures',
    price: 12,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.6,
    imageUrl: 'assets/food-sangah.jpg',
    tags: ['Traditionnel', 'Dîner','Végétarien'],
  },
  {
    id: '11',
    name: 'Kondre',
    cookTime: '2 heures',
    price: 12,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.6,
    imageUrl: 'assets/food-kondre.jpg',
    tags: ['Traditionnel', 'Dîner'],
  },
  {
    id: '12',
    name: 'fufu sauce gombo',
    cookTime: '2 heures',
    price: 12,
    favorite: true,
    origins: ['Cameroun'],
    stars: 4.6,
    imageUrl: 'assets/food-fufu-sauce-gombo.jpg',
    tags: ['Traditionnel', 'Dîner'],
  }
]

export const sample_tags: Tag[] = [
  { name: 'All', count: 12 }, // Total de tous les plats listés
  { name: 'Traditionnel', count: 9 }, // Ndolé et plantains, Eru, Koki, Poisson Braisé, Taro et sauce jaune
  { name: 'Dîner', count: 10 }, // La plupart sont appropriés pour le dîner
  { name: 'Festif', count: 1 }, // Poulet DG
  { name: 'Végétarien', count: 3 }, // Koki
  { name: 'StreetFood', count: 2 }, // Brochettes de Soya, Beignets Haricots
];
